Repository osamhack2022/WEB_APP_Goondae-goonde_Open-mind, pull requests merged in 2022-09, with the labels that each got.

#1 feature: 기본 틀 구현
  .gitignore
  .vscode/settings.json
  WEB(FE)/.eslintrc
  WEB(FE)/.gitignore
  WEB(FE)/dist/output.css
  WEB(FE)/package-lock.json
  WEB(FE)/package.json
  WEB(FE)/postcss.config.js
  WEB(FE)/prettierrc.js
  WEB(FE)/public/favicon.ico
  WEB(FE)/public/index.html
  WEB(FE)/public/logo192.png
  WEB(FE)/public/logo512.png
  WEB(FE)/public/manifest.json
  WEB(FE)/public/robots.txt
  WEB(FE)/src/App.jsx
  WEB(FE)/src/components/auth/AuthForm.jsx
  WEB(FE)/src/components/common/Drawer.jsx
  WEB(FE)/src/components/common/Footer.jsx
  WEB(FE)/src/components/common/Header.jsx
  WEB(FE)/src/components/common/Search.jsx
  WEB(FE)/src/containers/common/DrawerContainer.jsx
  WEB(FE)/src/containers/common/FooterContainer.jsx
  WEB(FE)/src/containers/common/HeaderContainer.jsx
  WEB(FE)/src/index.css
  WEB(FE)/src/index.js
  WEB(FE)/src/pages/LoginPage.jsx
  WEB(FE)/src/pages/Mainpage.jsx
  WEB(FE)/src/pages/RegisterPage.jsx
  WEB(FE)/tailwind.config.js
Labels: feature

#2 Edit/readme
  README.md
Labels: documentation

#3 feature: introPage 구현
  WEB(FE)/public/img/osam1.jpg
  WEB(FE)/public/img/osam2.jpg
  WEB(FE)/public/img/osam3.jpg
  WEB(FE)/public/img/osam4.png
  WEB(FE)/public/index.html
  WEB(FE)/src/components/auth/AuthForm.jsx
  WEB(FE)/src/components/common/Drawer.jsx
  WEB(FE)/src/components/common/Footer.jsx
  WEB(FE)/src/components/common/Header.jsx
  WEB(FE)/src/components/intro/IntroMain.jsx
  WEB(FE)/src/components/intro/IntroOne.jsx
  WEB(FE)/src/components/intro/IntroTwo.jsx
  WEB(FE)/src/containers/common/HeaderContainer.jsx
  WEB(FE)/src/containers/intro/ItemsContainer.jsx
  WEB(FE)/src/lib/img/osam1.jpg
  WEB(FE)/src/lib/img/osam2.jpg
  WEB(FE)/src/lib/img/osam3.jpg
  WEB(FE)/src/lib/img/osam4.png
  WEB(FE)/src/pages/Mainpage.jsx
  package-lock.json
  package.json
Labels: feature

#4 hotfix: Navbar fixed z-index 설정
  WEB(FE)/src/components/common/Header.jsx
  WEB(FE)/src/pages/Mainpage.jsx
Labels: hotfix

#24 edit: readme painpoint,solution update
  README.md
Labels: documentation

#26 feat: API 문서화하기
  WEB(BE)/myboard/__pycache__/__init__.cpython-310.pyc
  WEB(BE)/myboard/__pycache__/settings.cpython-310.pyc
  WEB(BE)/myboard/__pycache__/urls.cpython-310.pyc
  WEB(BE)/myboard/__pycache__/wsgi.cpython-310.pyc
  WEB(BE)/myboard/settings.py
  WEB(BE)/myboard/urls.py
  WEB(BE)/posts/__pycache__/__init__.cpython-310.pyc
  WEB(BE)/posts/__pycache__/admin.cpython-310.pyc
  WEB(BE)/posts/__pycache__/apps.cpython-310.pyc
  WEB(BE)/posts/__pycache__/models.cpython-310.pyc
  WEB(BE)/posts/__pycache__/permissions.cpython-310.pyc
  WEB(BE)/posts/__pycache__/serializers.cpython-310.pyc
  WEB(BE)/posts/__pycache__/urls.cpython-310.pyc
  WEB(BE)/posts/__pycache__/views.cpython-310.pyc
  WEB(BE)/posts/admin.py
  WEB(BE)/posts/migrations/__pycache__/0001_initial.cpython-310.pyc
  WEB(BE)/posts/migrations/__pycache__/0002_alter_post_image.cpython-310.pyc
  WEB(BE)/posts/migrations/__pycache__/__init__.cpython-310.pyc
  WEB(BE)/users/__pycache__/__init__.cpython-310.pyc
  WEB(BE)/users/__pycache__/admin.cpython-310.pyc
  WEB(BE)/users/__pycache__/apps.cpython-310.pyc
  WEB(BE)/users/__pycache__/models.cpython-310.pyc
  WEB(BE)/users/__pycache__/serializers.cpython-310.pyc
  WEB(BE)/users/__pycache__/urls.cpython-310.pyc
  WEB(BE)/users/__pycache__/views.cpython-310.pyc
  WEB(BE)/users/migrations/__pycache__/0001_initial.cpython-310.pyc
  WEB(BE)/users/migrations/__pycache__/0002_alter_profile_image.cpython-310.pyc
  WEB(BE)/users/migrations/__pycache__/0003_alter_profile_image.cpython-310.pyc
  WEB(BE)/users/migrations/__pycache__/__init__.cpython-310.pyc
Labels: feature
