Repository osamhack2022/WEB_APP_Goondae-goonde_Open-mind, pull requests merged in 2022-10, with the labels that each got.

#33 Crawler DB to DRF
  .gitignore
  .vscode/settings.json
  WEB(BE)/locations/__init__.py
  WEB(BE)/locations/admin.py
  WEB(BE)/locations/apps.py
  WEB(BE)/locations/migrations/__init__.py
  WEB(BE)/locations/models.py
  WEB(BE)/locations/serializers.py
  WEB(BE)/locations/tests.py
  WEB(BE)/locations/urls.py
  WEB(BE)/locations/views.py
  WEB(BE)/myboard/router.py
  WEB(BE)/myboard/settings.py
  WEB(BE)/myboard/urls.py
Labels: feature

#35 feature: kakaoMap 기본 화면 불러오기
  WEB(FE)/public/index.html
  WEB(FE)/src/containers/maps/kakao.jsx
Labels: feature

#38 fix: backend DB 단일화
  WEB(BE)/db.sqlite3
  WEB(BE)/locations/migrations/0001_initial.py
  WEB(BE)/myboard/router.py
  WEB(BE)/myboard/settings.py
Labels: hotfix

#50 hotfix: 추가 conflict 제거
  WEB(FE)/package-lock.json
  WEB(FE)/package.json
  WEB(FE)/postcss.config.js
  WEB(FE)/prettierrc.js
  WEB(FE)/readme.md
  WEB(FE)/src/App.jsx
  WEB(FE)/src/components/write/Editor.jsx
  WEB(FE)/src/containers/posts/PaginationContainer.jsx
  WEB(FE)/src/containers/posts/PostList.jsx
  WEB(FE)/src/containers/write/EditorContainer.jsx
  WEB(FE)/src/containers/write/WriteActionButtonsContainer.jsx
  WEB(FE)/src/lib/api/posts.js
  WEB(FE)/src/modules/write.js
  WEB(FE)/tailwind.config.js
Labels: hotfix

#52 feature: boardList 구형
  WEB(FE)/src/components/common/Pagination.jsx
  WEB(FE)/src/components/common/SubInfo.jsx
  WEB(FE)/src/containers/posts/PaginationContainer.jsx
  WEB(FE)/src/containers/posts/PostList.jsx
  WEB(FE)/src/containers/posts/PostListContainer.jsx
  WEB(FE)/src/containers/write/WriteActionButtonsContainer.jsx
  WEB(FE)/src/lib/api/posts.js
  WEB(FE)/src/modules/posts.js
  WEB(FE)/src/pages/WritePage.jsx
Labels: feature

#84 Feature/login register
  WEB(FE)/src/components/loading/LoadingPost.jsx
  WEB(FE)/src/components/place/Place.jsx
  WEB(FE)/src/components/post/Like.jsx
  WEB(FE)/src/components/post/PostViewer.jsx
  WEB(FE)/src/components/review/ReviewModal.jsx
  WEB(FE)/src/containers/auth/RegisterForm.jsx
  WEB(FE)/src/containers/place/PlaceContainer.jsx
  WEB(FE)/src/containers/placeList/PaginationContainer.jsx
  WEB(FE)/src/containers/post/LikeContainer.jsx
  WEB(FE)/src/containers/review/ReviewContainer.jsx
  WEB(FE)/src/lib/api/posts.js
  WEB(FE)/src/lib/img/like.png
  WEB(FE)/src/modules/post.js
  WEB(FE)/src/pages/PlacePage.jsx
  WEB(FE)/src/pages/PostPage.jsx
Labels: feature, hotfix

#96 feature: 지도 이동 시 검색 기능
  WEB(FE)/src/components/place/Place.jsx
  WEB(FE)/src/containers/map/MapContainer.jsx
  WEB(FE)/src/containers/map/MyLocationMapContainer.jsx
  WEB(FE)/src/containers/place/PlaceContainer.jsx
  WEB(FE)/src/lib/api/markers.js
  WEB(FE)/src/lib/hooks/useDebouncedEffect.jsx
  WEB(FE)/src/modules/index.js
  WEB(FE)/src/modules/markers.js
Labels: feature

#111 edit: readme TEAM_INFO 수정
  README.md
  img/TEAM_INFO.png
Labels: documentation

#113 hotfix: 이메일 확인 페이지로 이동
  WEB(FE)/src/App.jsx
  WEB(FE)/src/components/auth/EmailConfirm.jsx
  WEB(FE)/src/containers/auth/RegisterForm.jsx
  WEB(FE)/src/pages/EmailConfirmPage.jsx
Labels: hotfix

#122 edit:readme 수정_3
  README.md
  img/IA_IMAGE.png
  img/WIREFRAME_IMAGE.png
Labels: documentation

#127 hotfix: 오타 및 링크 수정
  README.md
Labels: hotfix

#139 edit: readme 내 유투브 이미지 수정
  README.md
  img/YOUTUBE.png
Labels: documentation

#140 edit: readme 내 프론트 로컬 실행 방법 추가
  README.md
  WEB(FE)/public/index.html
Labels: documentation
